### ISSUE TITLE
What about works, relationships...?

### ISSUE THREAD

**Issue by Sendoushi** [maxkueng/node-musicbrainz#24]
I'm doing a search by artist.

``` js
mb.searchArtists(query, filters, (err, artists) => {});
```

But that search is returning an empty array for works, relationships, discography... 
How can I fill all that information?

**Comment by richdunajewski** [comment]
I know it's a late response, but in case it helps anyone... 

Take the array of artists that you get back from `mb.searchArtists()` and then iterate through each one, calling `mb.lookupArtist()` using the **artist.id** returned by the previous call. In that lookup call, you can specify which relationships you want the API to return.

**Comment by maxkueng** [comment]
If you call `mb.searchArtists(...)` you should be getting instances of `Artist`, which is a subclass of `Resource`. However, these resources fully expanded yet. Every instance of `Resource` has a `resource.load(linkedEntities, force, callback)`. "work" is a linked entity of "artist".

The reason why the `artist.works` is empty in search results is because the MusicBrainz API doesn't include them in search results, and fetching them during search would require additional calls to the API that you might not need. There are rate limits on this API and it's also known to be very slow, so linked entities need to be loaded explicitly.

The following should work:

```js
mb.searchArtists(
  'The White Stripes',
  { country: 'US' },
  function(err, artists) {
    const firstResult = artists[0];

    // artist.works is empty array
    console.log(firstResult.works.length);

    firstResult.load(['works'], function(err) {
      // artist.works now has a few entries
      console.log(firstResult.works.length);
    });
  },
);
```
